insert into finite_load_sum values (
  :contract,
  :work_center_no,
  :work_day,
  --
  :capacity,
  :maintenance,
  :capacity_available,
  :capacity_consumed,
  --
  :load_from_ms,
  :load_from_mrp,
  :load_from_man,
  :load_from_inv,
  :load_from_nld,
  :load_from_mso,
  :load_from_dop,
  :load_from_pso,
  :load_from_rso,
  :load_from_psc,
  :load_from_pmrp,
  --
  sysdate
)
